skip_local_validator = true

[toolchain]

[features]
resolution = true
skip-lint = false

[programs.localnet]
stockforge = "5qNeAcUKD45g3T5osCLVk13Q8CZLtT7BWhivG5og9CMf"

[programs.devnet]
stockforge = "5qNeAcUKD45g3T5osCLVk13Q8CZLtT7BWhivG5og9CMf"

[provider]
cluster = "devnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "cargo test"

[hooks]
